version: '3.8'

services:
  # The Python FastAPI + PyTorch Backend
  backend:
    image: lung-cancer-backend:latest
    ports:
      - "8000:8000"
    restart: always

  # The Flutter Web Frontend
  frontend:
    image: lung-cancer-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always